"""Render a T2 tile schedule as CuTe DSL source.

One CTA owns one segment element; one thread owns one channel. Non-channel trailing axes are
unrolled into per-thread registers exactly as in T1, so this shares T1's scalar-expression model
and differs only in that the channel coordinate is the symbolic `c` rather than a literal.

Correctness-first (Phase 2 discipline): sums over the contracted channel axis are emitted fully
expanded, so the arithmetic order matches the interpreter's `einsum` reduction order closely
enough to be checked, and nothing depends on loop-carried SSA in the DSL. Vectorized loads,
multi-edge CTAs and MMA atoms are performance variants that come after bit-exactness.
"""

from __future__ import annotations

import textwrap

from codegen.emit import DTYPE, GENERATED_DIR, build_kernel
from codegen.tile import CH, TileSchedule
from zippel.ir import IndexType, Program


def _sym(buf: str, idx: tuple) -> str:
    return f"v_{buf}" + "".join(f"_{'c' if i == CH else i}" for i in idx)


def _smem(buf: str, idx: tuple) -> str:
    """A staged value belonging to another thread: `s_<buf>_<unrolled idx>[k]`."""
    fixed = "".join(f"_{i}" for i in idx if i != CH)
    ch = [i for i in idx if i != CH]
    return f"s_{buf}{fixed}"


def _ref(prog: Program, buf: str, idx: tuple) -> str:
    t = prog.type_of(buf)
    lead = "e" if t.segment != "none" else "0"
    coords = [lead] + [("c" if i == CH else str(i)) for i in idx]
    return f"m_{buf}[{', '.join(coords)}]"


def _factor(prog: Program, buf: str, idx: tuple, from_smem: bool, staged_shape) -> str:
    if from_smem:
        # the channel coordinate of a cross-channel read is a literal; that is the smem index
        chan = [i for i in idx if i != CH]
        others = [i for i in idx if i == CH]
        del others
        return f"s_{buf}[{chan[0]}]" if len(chan) == 1 else \
               f"s_{buf}[{', '.join(str(i) for i in chan)}]"
    return _sym(buf, idx)


def emit_tile_source(prog: Program, sched: TileSchedule, dtype: str = "f32") -> str:
    spec = sched.spec
    dt = DTYPE[dtype]
    C = sched.extent
    depth = max((len(a.terms) for a in sched.assigns), default=1)

    tensors = [b for b in spec.live_in if not isinstance(prog.type_of(b), IndexType)]
    tensors += list(spec.live_out)
    params = ", ".join(f"m_{b}: cute.Tensor" for b in tensors)

    # which (buffer, index) pairs are read straight from gmem, per thread
    wanted: dict[str, set[tuple]] = {}
    for a in sched.assigns:
        for t in a.terms:
            for buf, idx, from_smem in t.factors:
                if not from_smem and buf in spec.live_in:
                    wanted.setdefault(buf, set()).add(idx)
        if a.source is not None and a.source[0] in spec.live_in:
            wanted.setdefault(a.source[0], set()).add(a.source[1])

    body: list[str] = []
    for buf in spec.live_in:
        for idx in sorted(wanted.get(buf, ()), key=str):
            body.append(f"{_sym(buf, idx)} = {_ref(prog, buf, idx)}")

    for i, a in enumerate(sched.assigns):
        for buf in sched.stage_before.get(i, []):
            body.append(f"s_{buf}[c] = {_sym(buf, (CH,))}")
            body.append("cute.arch.barrier()")
        if a.fn is not None:
            arg = _sym(*a.source)
            body.append(f"{_sym(a.target, a.index)} = {_scalar(a.fn, arg, dt)}")
        elif not a.terms:
            body.append(f"{_sym(a.target, a.index)} = {dt}(0.0)")
        else:
            parts = []
            for t in a.terms:
                fs = " * ".join(_factor(prog, b, ix, sm, C) for b, ix, sm in t.factors)
                parts.append(fs if t.coeff == 1.0 else
                             (f"-({fs})" if t.coeff == -1.0 else f"{dt}({t.coeff!r}) * {fs}"))
            body.append(f"{_sym(a.target, a.index)} = " + " + ".join(parts))

    for buf in spec.live_out:
        t = prog.type_of(buf)
        import itertools
        ranges = [(CH,) if k == sched.axis else range(s) for k, s in enumerate(t.sizes)]
        for idx in itertools.product(*ranges):
            body.append(f"{_ref(prog, buf, tuple(idx))} = {_sym(buf, tuple(idx))}")

    smem_decls = "\n".join(
        f"        s_{b} = smem.allocate_tensor({dt}, cute.make_layout({C}), 16)"
        for b in sched.staged)
    indented = textwrap.indent("\n".join(body), " " * 12)

    return f'''"""Generated by codegen/emit_tile.py from fusion group {spec.name} (template T2).

{spec}
  channel axis {sched.axis} of extent {C} on threads; {sched.n_values} values,
  {sched.n_terms} terms. Staged through smem: {", ".join(sched.staged) or "(none)"}.
  Internal buffers never stored: {", ".join(spec.internal) or "(none)"}
"""

import cutlass
import cutlass.cute as cute
import cutlass.utils as cutlass_utils
from cutlass import Float32, Float64, Int32, const_expr
from cutlass.cute.runtime import from_dlpack

CHANNELS = {C}
TENSOR_ORDER = {tensors!r}

#: Correctness contract for this kernel (DECISIONS.md D25). A channel contraction cannot be
#: bit-exact against a blocked einsum, so the bar is the ordering bound the harness derives
#: from REDUCTION_DEPTH and the real input magnitudes.
TEMPLATE = "T2"
REDUCTION_DEPTH = {depth}
EXACT = False


class Kernel:
    """One CTA per {spec.segment}, one thread per channel."""

    @cute.jit
    def __call__(self, {params}, n_seg: Int32, stream):
        self.kernel({", ".join(f"m_{b}" for b in tensors)}, n_seg).launch(
            grid=[n_seg, 1, 1], block=[CHANNELS, 1, 1], stream=stream)

    @cute.kernel
    def kernel(self, {params}, n_seg: Int32):
        c, _, _ = cute.arch.thread_idx()
        e, _, _ = cute.arch.block_idx()
        smem = cutlass_utils.SmemAllocator()
{smem_decls}
        if e < n_seg:
{indented}
'''


def _scalar(fn: str, arg: str, dt: str) -> str:
    from codegen.emit import _fn_expr
    return _fn_expr(fn, 0, arg, dt)


__all__ = ["emit_tile_source", "build_kernel", "GENERATED_DIR"]
